version: '2'
services:
  mesistant:
    container_name: mesistant
    restart: always
    image: "prokuma/mesistant:latest"
    privileged: true
    tty: true
    ports:
      - "8080:8080"
  db:
    container_name: mesistant_db
    image: "mongo"
    restart: always
    ports:
        - "27017:27017" 
    volumes:
      - "./data:/data/db"

networks:
  default:
    external:
      name: shared
